name: Build Angular App
on:
  workflow_call:
    outputs:
      artifact_name:
        description: "The name of the build artifact"
        value: ${{ jobs.build.outputs.artifact_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: "angular-app-${{ github.run_id }}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Angular app
        run: npm run build
      
      - name: Copy web.config
        run: |
          # Create web.config if it doesn't exist
          if [ ! -f "web.config" ]; then
            cat > web.config << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Angular Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="./index.html" />
        </rule>
      </rules>
    </rewrite>
    <staticContent>
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
    </staticContent>
  </system.webServer>
</configuration>
EOF
          fi
          # Copy web.config to build output
          cp web.config dist/ng17-test/browser/
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: "angular-app-${{ github.run_id }}"
          path: dist/ng17-test/browser/
