name: Build Azure Static Web App
on:
  workflow_call:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Build
        id: build
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SEA_0C5BD660F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          api_location: ""
          output_location: "dist/ng17-test/browser"
          # skip_deploy_on_missing_secrets: true
