name: Deploy to Azure Static Web App
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to (e.g., dev, qa, prod)"
      artifact-name:
        required: true
        type: string
        description: "The name of the artifact to download"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/ng17-test/browser
      
      - name: Deploy to Azure Static Web App
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SEA_0C5BD660F }}
          action: "upload"
          app_location: "dist/ng17-test/browser"
          api_location: ""
          skip_app_build: true
