name: Azure Web App CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      app-name: 'ng17Test'  # Replace with your Azure Web App name
      # slot-name: 'production'  # Optional, defaults to production
      artifact-name: ${{ needs.build.outputs.artifact_name }}
    secrets: inherit
