name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/build.yml

  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/deploy.yml
