name: Security Scan test1

on:
  push:
    branches: master
  workflow_dispatch:  # Allow manual triggers
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
          chmod +x ./snyk
          sudo mv ./snyk /usr/local/bin/
      
            # Run Snyk to check for code vulnerabilities and generate report
      - name: Snyk Code Test
        run: snyk code test
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Dependencies Test
        run: snyk test --all-projects
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
